name: Wait

description: Wait some duration of time

inputs:
  milliseconds:
    description: number of milliseconds to wait
    required: true
    default: 1000

outputs:
  time:
    description: the current time after waiting

runs:
  using: node16
  main: dist/index.js
